### ISSUE TITLE
 Inserting special characters from prompt into SQL translation

### ISSUE THREAD

**Issue by FrancescoRovito** [Jhonnyr97/AIChatSQL#7]
Hi, I really appreciate your work and I would like to use it but I've encountered some problems so, I would like to ask you a few questions to support me.
When I write a prompt, the translation into SQL is incorrect because special characters (like backticks in the example) are inserted. As a result, Cheshire Cat doesn't respond correctly. Why does this happen? How can I clean the query of special characters and ensure it executes correctly so, Cheshire Cat provides the right answer? Should I take action on LangChain? Can you give me some suggestions? 
The initial prompt is: database/how many databases do we have?
Thank you.
![image (32)](https://github.com/user-attachments/assets/dcc3be08-0243-485b-9c54-0f8f7b1082c3)

**Comment by Jhonnyr97** [comment]
This issue seems related to the model you are using. Can you specify which LLM model you are using?
